openapi: "3.0.0"

info:
  $ref: "./info.yaml"

servers:
  - url: http://localhost:{port}
    description: Local
    variables:
      port:
        enum: ["3000", "8080"]
        default: "3000"
  - url: https://bandori.party/api
    description: Production

tags:
- name: endpoints
  description: Endpoints
- name: members
  description: Band Members
- name: cards
  description: Game Cards

paths:
  $ref: "./paths.yaml"

components:
  headers:
    cache-control:
      schema:
        type: string
        example: private
    content-language:
      schema:
        type: string
        enum: ["en", "ja"]
        example: en
    content-type:
      schema:
        type: string
        example: application/json; charset=utf-8
    cf-cache-status:
      schema:
        type: string
        example: DYNAMIC
    vary:
      schema:
        type: string
        example: Accept-Language, Cookie
  schemas:
    $ref: "./schemas.yaml"
